const currencySymbols = [
  {
    symbol: 'AED',
    code: 'AED',
    symbol_native: 'د.إ.‏',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'AFN',
    code: 'AFN',
    symbol_native: '؋',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'ALL',
    code: 'ALL',
    symbol_native: 'Lekë',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'AMD',
    code: 'AMD',
    symbol_native: '֏',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'ANG',
    code: 'ANG',
    symbol_native: 'NAf.',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'AOA',
    code: 'AOA',
    symbol_native: 'Kz',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'ARS',
    code: 'ARS',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'AU$',
    code: 'AUD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'AWG',
    code: 'AWG',
    symbol_native: 'Afl.',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'AZN',
    code: 'AZN',
    symbol_native: '₼',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'BAM',
    code: 'BAM',
    symbol_native: 'КМ',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'BBD',
    code: 'BBD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'BDT',
    code: 'BDT',
    symbol_native: '৳',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'BGN',
    code: 'BGN',
    symbol_native: 'лв.',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'BHD',
    code: 'BHD',
    symbol_native: 'د.ب.‏',
    decimal_digits: 3,
    rounding: 0.0,
  },
  {
    symbol: 'BIF',
    code: 'BIF',
    symbol_native: 'FBu',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'BMD',
    code: 'BMD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'BND',
    code: 'BND',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'BOB',
    code: 'BOB',
    symbol_native: 'Bs',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'BOV',
    code: 'BOV',
    symbol_native: 'BOV',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'R$',
    code: 'BRL',
    symbol_native: 'R$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'BSD',
    code: 'BSD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'BTN',
    code: 'BTN',
    symbol_native: 'Nu.',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'BWP',
    code: 'BWP',
    symbol_native: 'P',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'BYN',
    code: 'BYN',
    symbol_native: 'Br',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'BZD',
    code: 'BZD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'CA$',
    code: 'CAD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'CDF',
    code: 'CDF',
    symbol_native: 'FC',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'CHE',
    code: 'CHE',
    symbol_native: 'CHE',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'CHF',
    code: 'CHF',
    symbol_native: 'CHF',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'CHW',
    code: 'CHW',
    symbol_native: 'CHW',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'CLF',
    code: 'CLF',
    symbol_native: 'CLF',
    decimal_digits: 4,
    rounding: 0.0,
  },
  {
    symbol: 'CLP',
    code: 'CLP',
    symbol_native: '$',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'CNH',
    code: 'CNH',
    symbol_native: 'CNH',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'CN¥',
    code: 'CNY',
    symbol_native: '¥',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'COP',
    code: 'COP',
    symbol_native: '$',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'COU',
    code: 'COU',
    symbol_native: 'COU',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'CRC',
    code: 'CRC',
    symbol_native: '₡',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'CUC',
    code: 'CUC',
    symbol_native: 'CUC',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'CUP',
    code: 'CUP',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'CVE',
    code: 'CVE',
    symbol_native: '​',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'CZK',
    code: 'CZK',
    symbol_native: 'Kč',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'DJF',
    code: 'DJF',
    symbol_native: 'Fdj',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'DKK',
    code: 'DKK',
    symbol_native: 'kr.',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'DOP',
    code: 'DOP',
    symbol_native: 'RD$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'DZD',
    code: 'DZD',
    symbol_native: 'د.ج.‏',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'EGP',
    code: 'EGP',
    symbol_native: 'ج.م.‏',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'ERN',
    code: 'ERN',
    symbol_native: 'Nfk',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'ETB',
    code: 'ETB',
    symbol_native: 'ብር',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: '€',
    code: 'EUR',
    symbol_native: '€',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'FJD',
    code: 'FJD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'FKP',
    code: 'FKP',
    symbol_native: '£',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: '£',
    code: 'GBP',
    symbol_native: '£',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'GEL',
    code: 'GEL',
    symbol_native: '₾',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'GHS',
    code: 'GHS',
    symbol_native: 'GH₵',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'GIP',
    code: 'GIP',
    symbol_native: '£',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'GMD',
    code: 'GMD',
    symbol_native: 'D',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'GNF',
    code: 'GNF',
    symbol_native: 'FG',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'GTQ',
    code: 'GTQ',
    symbol_native: 'Q',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'GYD',
    code: 'GYD',
    symbol_native: '$',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'HK$',
    code: 'HKD',
    symbol_native: 'HK$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'HNL',
    code: 'HNL',
    symbol_native: 'L',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'HRK',
    code: 'HRK',
    symbol_native: 'HRK',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'HTG',
    code: 'HTG',
    symbol_native: 'G',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'HUF',
    code: 'HUF',
    symbol_native: 'Ft',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'IDR',
    code: 'IDR',
    symbol_native: 'Rp',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: '₪',
    code: 'ILS',
    symbol_native: '₪',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: '₹',
    code: 'INR',
    symbol_native: '₹',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'IQD',
    code: 'IQD',
    symbol_native: 'د.ع.‏',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'IRR',
    code: 'IRR',
    symbol_native: 'IRR',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'ISK',
    code: 'ISK',
    symbol_native: 'ISK',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'JMD',
    code: 'JMD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'JOD',
    code: 'JOD',
    symbol_native: 'د.أ.‏',
    decimal_digits: 3,
    rounding: 0.0,
  },
  {
    symbol: 'JP¥',
    code: 'JPY',
    symbol_native: '￥',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'KES',
    code: 'KES',
    symbol_native: 'Ksh',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'KGS',
    code: 'KGS',
    symbol_native: 'сом',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'KHR',
    code: 'KHR',
    symbol_native: '៛',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'KMF',
    code: 'KMF',
    symbol_native: 'CF',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'KPW',
    code: 'KPW',
    symbol_native: 'KPW',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: '₩',
    code: 'KRW',
    symbol_native: '₩',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'KWD',
    code: 'KWD',
    symbol_native: 'د.ك.‏',
    decimal_digits: 3,
    rounding: 0.0,
  },
  {
    symbol: 'KYD',
    code: 'KYD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'KZT',
    code: 'KZT',
    symbol_native: '₸',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'LAK',
    code: 'LAK',
    symbol_native: '₭',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'LBP',
    code: 'LBP',
    symbol_native: 'ل.ل.‏',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'LKR',
    code: 'LKR',
    symbol_native: 'රු.',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'LRD',
    code: 'LRD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'LSL',
    code: 'LSL',
    symbol_native: 'LSL',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'LYD',
    code: 'LYD',
    symbol_native: 'د.ل.‏',
    decimal_digits: 3,
    rounding: 0.0,
  },
  {
    symbol: 'MAD',
    code: 'MAD',
    symbol_native: 'د.م.‏',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'MDL',
    code: 'MDL',
    symbol_native: 'L',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'MGA',
    code: 'MGA',
    symbol_native: 'Ar',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'MKD',
    code: 'MKD',
    symbol_native: 'ден',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'MMK',
    code: 'MMK',
    symbol_native: 'K',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'MNT',
    code: 'MNT',
    symbol_native: '₮',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'MOP',
    code: 'MOP',
    symbol_native: 'MOP$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'MRO',
    code: 'MRO',
    symbol_native: 'أ.م.‏',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'MUR',
    code: 'MUR',
    symbol_native: 'Rs',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'MWK',
    code: 'MWK',
    symbol_native: 'MK',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'MX$',
    code: 'MXN',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'MXV',
    code: 'MXV',
    symbol_native: 'MXV',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'MYR',
    code: 'MYR',
    symbol_native: 'RM',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'MZN',
    code: 'MZN',
    symbol_native: 'MTn',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'NAD',
    code: 'NAD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'NGN',
    code: 'NGN',
    symbol_native: '₦',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'NIO',
    code: 'NIO',
    symbol_native: 'C$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'NOK',
    code: 'NOK',
    symbol_native: 'kr',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'NPR',
    code: 'NPR',
    symbol_native: 'नेरू',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'NZ$',
    code: 'NZD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'OMR',
    code: 'OMR',
    symbol_native: 'ر.ع.‏',
    decimal_digits: 3,
    rounding: 0.0,
  },
  {
    symbol: 'PAB',
    code: 'PAB',
    symbol_native: 'B/.',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'PEN',
    code: 'PEN',
    symbol_native: 'S/',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'PGK',
    code: 'PGK',
    symbol_native: 'K',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'PHP',
    code: 'PHP',
    symbol_native: '₱',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'PKR',
    code: 'PKR',
    symbol_native: 'Rs',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'PLN',
    code: 'PLN',
    symbol_native: 'zł',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'PYG',
    code: 'PYG',
    symbol_native: 'Gs.',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'QAR',
    code: 'QAR',
    symbol_native: 'ر.ق.‏',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'RON',
    code: 'RON',
    symbol_native: 'RON',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'RSD',
    code: 'RSD',
    symbol_native: 'RSD',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'RUB',
    code: 'RUB',
    symbol_native: '₽',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'RWF',
    code: 'RWF',
    symbol_native: 'RF',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'SAR',
    code: 'SAR',
    symbol_native: 'ر.س.‏',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'SBD',
    code: 'SBD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'SCR',
    code: 'SCR',
    symbol_native: 'SR',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'SDG',
    code: 'SDG',
    symbol_native: 'ج.س.',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'SEK',
    code: 'SEK',
    symbol_native: 'kr',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'SGD',
    code: 'SGD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'SHP',
    code: 'SHP',
    symbol_native: '£',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'SLL',
    code: 'SLL',
    symbol_native: 'Le',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'SOS',
    code: 'SOS',
    symbol_native: 'S',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'SRD',
    code: 'SRD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'SSP',
    code: 'SSP',
    symbol_native: '£',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'STN',
    code: 'STN',
    symbol_native: 'STN',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'SYP',
    code: 'SYP',
    symbol_native: 'ل.س.‏',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'SZL',
    code: 'SZL',
    symbol_native: 'E',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: '฿',
    code: 'THB',
    symbol_native: 'THB',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'TJS',
    code: 'TJS',
    symbol_native: 'сом.',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'TND',
    code: 'TND',
    symbol_native: 'د.ت.‏',
    decimal_digits: 3,
    rounding: 0.0,
  },
  {
    symbol: 'TOP',
    code: 'TOP',
    symbol_native: 'T$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'TRY',
    code: 'TRY',
    symbol_native: '₺',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'TTD',
    code: 'TTD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'NT$',
    code: 'TWD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'TZS',
    code: 'TZS',
    symbol_native: 'TSh',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'UAH',
    code: 'UAH',
    symbol_native: '₴',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'UGX',
    code: 'UGX',
    symbol_native: 'USh',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'US$',
    code: 'USD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'USN',
    code: 'USN',
    symbol_native: 'USN',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'UYI',
    code: 'UYI',
    symbol_native: 'UYI',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'UYU',
    code: 'UYU',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'UZS',
    code: 'UZS',
    symbol_native: 'сўм',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'VEF',
    code: 'VEF',
    symbol_native: 'Bs.',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: '₫',
    code: 'VND',
    symbol_native: '₫',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'VUV',
    code: 'VUV',
    symbol_native: 'VT',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'WST',
    code: 'WST',
    symbol_native: 'WS$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'FCFA',
    code: 'XAF',
    symbol_native: 'FCFA',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'EC$',
    code: 'XCD',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'CFA',
    code: 'XOF',
    symbol_native: 'CFA',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'CFPF',
    code: 'XPF',
    symbol_native: 'FCFP',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'YER',
    code: 'YER',
    symbol_native: 'ر.ي.‏',
    decimal_digits: 0,
    rounding: 0.0,
  },
  {
    symbol: 'ZAR',
    code: 'ZAR',
    symbol_native: 'R',
    decimal_digits: 2,
    rounding: 0.0,
  },
  {
    symbol: 'ZMW',
    code: 'ZMW',
    symbol_native: 'K',
    decimal_digits: 2,
    rounding: 0.0,
  },
];
export {currencySymbols};
