name: 'Pipeline Meli Test Development'

on:
  push:
    branches:
      - '**'
      - '!master'

  tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key:
            ${{ runner.os }}-cache-node-modules-${{ hashFiles('./yarn.lock') }}
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
 