name: 'Pipeline Meli Development'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          path: ./node_modules
          key:
            ${{ runner.os }}-cache-node-modules-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-node-modules-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: yarn install
  tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-cache-node-modules-${{ hashFiles('./yarn.lock') }}
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
